apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - homecraft-backend.yaml
  - homecraft-frontend.yaml
  - homecraft-operator.yaml
# This directory is for Flux HelmRelease resources
# Example:
# - cert-manager.yaml
# - ingress-nginx.yaml
