apiVersion: v2
name: homecraft-backend
description: HomeCraft API - Kubernetes-native REST API for Minecraft servers
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - minecraft
  - kubernetes
  - api
maintainers:
  - name: NaoMauss
