{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "homecraft-backend.fullname" . }}
  labels:
    {{- include "homecraft-backend.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "homecraft-backend.fullname" . }}
  labels:
    {{- include "homecraft-backend.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "homecraft-backend.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "homecraft-backend.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "homecraft-backend.fullname" . }}-namespace-access
  namespace: minecraft-servers
  labels:
    {{- include "homecraft-backend.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "homecraft-backend.fullname" . }}-namespace-access
  namespace: minecraft-servers
  labels:
    {{- include "homecraft-backend.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "homecraft-backend.fullname" . }}-namespace-access
subjects:
  - kind: ServiceAccount
    name: {{ include "homecraft-backend.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
