apiVersion: v1
kind: Service
metadata:
  name: {{ include "homecraft-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "homecraft-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    control-plane: controller-manager
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "homecraft-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    control-plane: controller-manager
